/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the IbxPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IbxPage{}

// IbxPage struct for IbxPage
type IbxPage struct {
	Pagination           Pagination `json:"pagination"`
	Data                 []Ibx      `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _IbxPage IbxPage

// NewIbxPage instantiates a new IbxPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIbxPage(pagination Pagination, data []Ibx) *IbxPage {
	this := IbxPage{}
	this.Pagination = pagination
	this.Data = data
	return &this
}

// NewIbxPageWithDefaults instantiates a new IbxPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIbxPageWithDefaults() *IbxPage {
	this := IbxPage{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *IbxPage) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *IbxPage) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *IbxPage) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetData returns the Data field value
func (o *IbxPage) GetData() []Ibx {
	if o == nil {
		var ret []Ibx
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IbxPage) GetDataOk() ([]Ibx, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *IbxPage) SetData(v []Ibx) {
	o.Data = v
}

func (o IbxPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IbxPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IbxPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIbxPage := _IbxPage{}

	err = json.Unmarshal(data, &varIbxPage)

	if err != nil {
		return err
	}

	*o = IbxPage(varIbxPage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIbxPage struct {
	value *IbxPage
	isSet bool
}

func (v NullableIbxPage) Get() *IbxPage {
	return v.value
}

func (v *NullableIbxPage) Set(val *IbxPage) {
	v.value = val
	v.isSet = true
}

func (v NullableIbxPage) IsSet() bool {
	return v.isSet
}

func (v *NullableIbxPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIbxPage(val *IbxPage) *NullableIbxPage {
	return &NullableIbxPage{value: val, isSet: true}
}

func (v NullableIbxPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIbxPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
