/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the RoutingProtocolReadModelBgp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingProtocolReadModelBgp{}

// RoutingProtocolReadModelBgp struct for RoutingProtocolReadModelBgp
type RoutingProtocolReadModelBgp struct {
	Tags []string `json:"tags,omitempty"`
	// Routing protocol URI
	Href *string `json:"href,omitempty"`
	// Routing protocol identifier
	Uuid *string `json:"uuid,omitempty"`
	// Allowed values: - BGP - DIRECT - STATIC
	Type string `json:"type"`
	// Name of the routing protocol instance.
	Name string `json:"name"`
	// Description of the routing protocol instance
	Description *string              `json:"description,omitempty"`
	Ipv4        *RoutingProtocolIpv4 `json:"ipv4,omitempty"`
	Ipv6        *RoutingProtocolIpv6 `json:"ipv6,omitempty"`
	ChangeLog   ChangeLog            `json:"changeLog"`
	// Customer Autonomous System Number
	CustomerAsn      int64                                           `json:"customerAsn"`
	CustomerAsnRange *RoutingProtocolRequestBgpAllOfCustomerAsnRange `json:"customerAsnRange,omitempty"`
	// Equinix Autonomous System Number
	EquinixAsn int64 `json:"equinixAsn"`
	// BGP authentication key
	BgpAuthKey           *string      `json:"bgpAuthKey,omitempty"`
	ExportPolicy         ExportPolicy `json:"exportPolicy"`
	AdditionalProperties map[string]interface{}
}

type _RoutingProtocolReadModelBgp RoutingProtocolReadModelBgp

// NewRoutingProtocolReadModelBgp instantiates a new RoutingProtocolReadModelBgp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingProtocolReadModelBgp(type_ string, name string, changeLog ChangeLog, customerAsn int64, equinixAsn int64, exportPolicy ExportPolicy) *RoutingProtocolReadModelBgp {
	this := RoutingProtocolReadModelBgp{}
	this.Type = type_
	this.Name = name
	this.ChangeLog = changeLog
	this.CustomerAsn = customerAsn
	this.EquinixAsn = equinixAsn
	this.ExportPolicy = exportPolicy
	return &this
}

// NewRoutingProtocolReadModelBgpWithDefaults instantiates a new RoutingProtocolReadModelBgp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingProtocolReadModelBgpWithDefaults() *RoutingProtocolReadModelBgp {
	this := RoutingProtocolReadModelBgp{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *RoutingProtocolReadModelBgp) SetTags(v []string) {
	o.Tags = v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *RoutingProtocolReadModelBgp) SetHref(v string) {
	o.Href = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *RoutingProtocolReadModelBgp) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value
func (o *RoutingProtocolReadModelBgp) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RoutingProtocolReadModelBgp) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *RoutingProtocolReadModelBgp) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoutingProtocolReadModelBgp) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutingProtocolReadModelBgp) SetDescription(v string) {
	o.Description = &v
}

// GetIpv4 returns the Ipv4 field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetIpv4() RoutingProtocolIpv4 {
	if o == nil || IsNil(o.Ipv4) {
		var ret RoutingProtocolIpv4
		return ret
	}
	return *o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetIpv4Ok() (*RoutingProtocolIpv4, bool) {
	if o == nil || IsNil(o.Ipv4) {
		return nil, false
	}
	return o.Ipv4, true
}

// HasIpv4 returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasIpv4() bool {
	if o != nil && !IsNil(o.Ipv4) {
		return true
	}

	return false
}

// SetIpv4 gets a reference to the given RoutingProtocolIpv4 and assigns it to the Ipv4 field.
func (o *RoutingProtocolReadModelBgp) SetIpv4(v RoutingProtocolIpv4) {
	o.Ipv4 = &v
}

// GetIpv6 returns the Ipv6 field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetIpv6() RoutingProtocolIpv6 {
	if o == nil || IsNil(o.Ipv6) {
		var ret RoutingProtocolIpv6
		return ret
	}
	return *o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetIpv6Ok() (*RoutingProtocolIpv6, bool) {
	if o == nil || IsNil(o.Ipv6) {
		return nil, false
	}
	return o.Ipv6, true
}

// HasIpv6 returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasIpv6() bool {
	if o != nil && !IsNil(o.Ipv6) {
		return true
	}

	return false
}

// SetIpv6 gets a reference to the given RoutingProtocolIpv6 and assigns it to the Ipv6 field.
func (o *RoutingProtocolReadModelBgp) SetIpv6(v RoutingProtocolIpv6) {
	o.Ipv6 = &v
}

// GetChangeLog returns the ChangeLog field value
func (o *RoutingProtocolReadModelBgp) GetChangeLog() ChangeLog {
	if o == nil {
		var ret ChangeLog
		return ret
	}

	return o.ChangeLog
}

// GetChangeLogOk returns a tuple with the ChangeLog field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetChangeLogOk() (*ChangeLog, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeLog, true
}

// SetChangeLog sets field value
func (o *RoutingProtocolReadModelBgp) SetChangeLog(v ChangeLog) {
	o.ChangeLog = v
}

// GetCustomerAsn returns the CustomerAsn field value
func (o *RoutingProtocolReadModelBgp) GetCustomerAsn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CustomerAsn
}

// GetCustomerAsnOk returns a tuple with the CustomerAsn field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetCustomerAsnOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerAsn, true
}

// SetCustomerAsn sets field value
func (o *RoutingProtocolReadModelBgp) SetCustomerAsn(v int64) {
	o.CustomerAsn = v
}

// GetCustomerAsnRange returns the CustomerAsnRange field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetCustomerAsnRange() RoutingProtocolRequestBgpAllOfCustomerAsnRange {
	if o == nil || IsNil(o.CustomerAsnRange) {
		var ret RoutingProtocolRequestBgpAllOfCustomerAsnRange
		return ret
	}
	return *o.CustomerAsnRange
}

// GetCustomerAsnRangeOk returns a tuple with the CustomerAsnRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetCustomerAsnRangeOk() (*RoutingProtocolRequestBgpAllOfCustomerAsnRange, bool) {
	if o == nil || IsNil(o.CustomerAsnRange) {
		return nil, false
	}
	return o.CustomerAsnRange, true
}

// HasCustomerAsnRange returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasCustomerAsnRange() bool {
	if o != nil && !IsNil(o.CustomerAsnRange) {
		return true
	}

	return false
}

// SetCustomerAsnRange gets a reference to the given RoutingProtocolRequestBgpAllOfCustomerAsnRange and assigns it to the CustomerAsnRange field.
func (o *RoutingProtocolReadModelBgp) SetCustomerAsnRange(v RoutingProtocolRequestBgpAllOfCustomerAsnRange) {
	o.CustomerAsnRange = &v
}

// GetEquinixAsn returns the EquinixAsn field value
func (o *RoutingProtocolReadModelBgp) GetEquinixAsn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EquinixAsn
}

// GetEquinixAsnOk returns a tuple with the EquinixAsn field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetEquinixAsnOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EquinixAsn, true
}

// SetEquinixAsn sets field value
func (o *RoutingProtocolReadModelBgp) SetEquinixAsn(v int64) {
	o.EquinixAsn = v
}

// GetBgpAuthKey returns the BgpAuthKey field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelBgp) GetBgpAuthKey() string {
	if o == nil || IsNil(o.BgpAuthKey) {
		var ret string
		return ret
	}
	return *o.BgpAuthKey
}

// GetBgpAuthKeyOk returns a tuple with the BgpAuthKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetBgpAuthKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BgpAuthKey) {
		return nil, false
	}
	return o.BgpAuthKey, true
}

// HasBgpAuthKey returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelBgp) HasBgpAuthKey() bool {
	if o != nil && !IsNil(o.BgpAuthKey) {
		return true
	}

	return false
}

// SetBgpAuthKey gets a reference to the given string and assigns it to the BgpAuthKey field.
func (o *RoutingProtocolReadModelBgp) SetBgpAuthKey(v string) {
	o.BgpAuthKey = &v
}

// GetExportPolicy returns the ExportPolicy field value
func (o *RoutingProtocolReadModelBgp) GetExportPolicy() ExportPolicy {
	if o == nil {
		var ret ExportPolicy
		return ret
	}

	return o.ExportPolicy
}

// GetExportPolicyOk returns a tuple with the ExportPolicy field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelBgp) GetExportPolicyOk() (*ExportPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportPolicy, true
}

// SetExportPolicy sets field value
func (o *RoutingProtocolReadModelBgp) SetExportPolicy(v ExportPolicy) {
	o.ExportPolicy = v
}

func (o RoutingProtocolReadModelBgp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingProtocolReadModelBgp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Ipv4) {
		toSerialize["ipv4"] = o.Ipv4
	}
	if !IsNil(o.Ipv6) {
		toSerialize["ipv6"] = o.Ipv6
	}
	toSerialize["changeLog"] = o.ChangeLog
	toSerialize["customerAsn"] = o.CustomerAsn
	if !IsNil(o.CustomerAsnRange) {
		toSerialize["customerAsnRange"] = o.CustomerAsnRange
	}
	toSerialize["equinixAsn"] = o.EquinixAsn
	if !IsNil(o.BgpAuthKey) {
		toSerialize["bgpAuthKey"] = o.BgpAuthKey
	}
	toSerialize["exportPolicy"] = o.ExportPolicy

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoutingProtocolReadModelBgp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"changeLog",
		"customerAsn",
		"equinixAsn",
		"exportPolicy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingProtocolReadModelBgp := _RoutingProtocolReadModelBgp{}

	err = json.Unmarshal(data, &varRoutingProtocolReadModelBgp)

	if err != nil {
		return err
	}

	*o = RoutingProtocolReadModelBgp(varRoutingProtocolReadModelBgp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "href")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "ipv4")
		delete(additionalProperties, "ipv6")
		delete(additionalProperties, "changeLog")
		delete(additionalProperties, "customerAsn")
		delete(additionalProperties, "customerAsnRange")
		delete(additionalProperties, "equinixAsn")
		delete(additionalProperties, "bgpAuthKey")
		delete(additionalProperties, "exportPolicy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoutingProtocolReadModelBgp struct {
	value *RoutingProtocolReadModelBgp
	isSet bool
}

func (v NullableRoutingProtocolReadModelBgp) Get() *RoutingProtocolReadModelBgp {
	return v.value
}

func (v *NullableRoutingProtocolReadModelBgp) Set(val *RoutingProtocolReadModelBgp) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingProtocolReadModelBgp) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingProtocolReadModelBgp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingProtocolReadModelBgp(val *RoutingProtocolReadModelBgp) *NullableRoutingProtocolReadModelBgp {
	return &NullableRoutingProtocolReadModelBgp{value: val, isSet: true}
}

func (v NullableRoutingProtocolReadModelBgp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingProtocolReadModelBgp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
