/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the ContactItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactItem{}

// ContactItem struct for ContactItem
type ContactItem struct {
	// Account URI
	Href *string         `json:"href,omitempty"`
	Type ContactItemType `json:"type"`
	// Identifies (e.g., contactId, userId, userKey) a registered user.
	RegisteredUser *string                  `json:"registeredUser,omitempty"`
	FirstName      *string                  `json:"firstName,omitempty"`
	LastName       *string                  `json:"lastName,omitempty"`
	Timezone       *string                  `json:"timezone,omitempty"`
	Availability   *ContactItemAvailability `json:"availability,omitempty"`
	// Describe any contact preferences
	Notes                *string              `json:"notes,omitempty"`
	Details              []ContactItemDetails `json:"details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ContactItem ContactItem

// NewContactItem instantiates a new ContactItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactItem(type_ ContactItemType) *ContactItem {
	this := ContactItem{}
	this.Type = type_
	return &this
}

// NewContactItemWithDefaults instantiates a new ContactItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactItemWithDefaults() *ContactItem {
	this := ContactItem{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ContactItem) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ContactItem) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ContactItem) SetHref(v string) {
	o.Href = &v
}

// GetType returns the Type field value
func (o *ContactItem) GetType() ContactItemType {
	if o == nil {
		var ret ContactItemType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContactItem) GetTypeOk() (*ContactItemType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContactItem) SetType(v ContactItemType) {
	o.Type = v
}

// GetRegisteredUser returns the RegisteredUser field value if set, zero value otherwise.
func (o *ContactItem) GetRegisteredUser() string {
	if o == nil || IsNil(o.RegisteredUser) {
		var ret string
		return ret
	}
	return *o.RegisteredUser
}

// GetRegisteredUserOk returns a tuple with the RegisteredUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetRegisteredUserOk() (*string, bool) {
	if o == nil || IsNil(o.RegisteredUser) {
		return nil, false
	}
	return o.RegisteredUser, true
}

// HasRegisteredUser returns a boolean if a field has been set.
func (o *ContactItem) HasRegisteredUser() bool {
	if o != nil && !IsNil(o.RegisteredUser) {
		return true
	}

	return false
}

// SetRegisteredUser gets a reference to the given string and assigns it to the RegisteredUser field.
func (o *ContactItem) SetRegisteredUser(v string) {
	o.RegisteredUser = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *ContactItem) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *ContactItem) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *ContactItem) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *ContactItem) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *ContactItem) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *ContactItem) SetLastName(v string) {
	o.LastName = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *ContactItem) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *ContactItem) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *ContactItem) SetTimezone(v string) {
	o.Timezone = &v
}

// GetAvailability returns the Availability field value if set, zero value otherwise.
func (o *ContactItem) GetAvailability() ContactItemAvailability {
	if o == nil || IsNil(o.Availability) {
		var ret ContactItemAvailability
		return ret
	}
	return *o.Availability
}

// GetAvailabilityOk returns a tuple with the Availability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetAvailabilityOk() (*ContactItemAvailability, bool) {
	if o == nil || IsNil(o.Availability) {
		return nil, false
	}
	return o.Availability, true
}

// HasAvailability returns a boolean if a field has been set.
func (o *ContactItem) HasAvailability() bool {
	if o != nil && !IsNil(o.Availability) {
		return true
	}

	return false
}

// SetAvailability gets a reference to the given ContactItemAvailability and assigns it to the Availability field.
func (o *ContactItem) SetAvailability(v ContactItemAvailability) {
	o.Availability = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *ContactItem) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *ContactItem) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *ContactItem) SetNotes(v string) {
	o.Notes = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *ContactItem) GetDetails() []ContactItemDetails {
	if o == nil || IsNil(o.Details) {
		var ret []ContactItemDetails
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactItem) GetDetailsOk() ([]ContactItemDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ContactItem) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []ContactItemDetails and assigns it to the Details field.
func (o *ContactItem) SetDetails(v []ContactItemDetails) {
	o.Details = v
}

func (o ContactItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.RegisteredUser) {
		toSerialize["registeredUser"] = o.RegisteredUser
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Availability) {
		toSerialize["availability"] = o.Availability
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContactItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContactItem := _ContactItem{}

	err = json.Unmarshal(data, &varContactItem)

	if err != nil {
		return err
	}

	*o = ContactItem(varContactItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		delete(additionalProperties, "type")
		delete(additionalProperties, "registeredUser")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "availability")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContactItem struct {
	value *ContactItem
	isSet bool
}

func (v NullableContactItem) Get() *ContactItem {
	return v.value
}

func (v *NullableContactItem) Set(val *ContactItem) {
	v.value = val
	v.isSet = true
}

func (v NullableContactItem) IsSet() bool {
	return v.isSet
}

func (v *NullableContactItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactItem(val *ContactItem) *NullableContactItem {
	return &NullableContactItem{value: val, isSet: true}
}

func (v NullableContactItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
