/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the RoutingProtocolReadModelStatic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingProtocolReadModelStatic{}

// RoutingProtocolReadModelStatic struct for RoutingProtocolReadModelStatic
type RoutingProtocolReadModelStatic struct {
	Tags []string `json:"tags,omitempty"`
	// Routing protocol URI
	Href *string `json:"href,omitempty"`
	// Routing protocol identifier
	Uuid *string `json:"uuid,omitempty"`
	// Allowed values: - BGP - DIRECT - STATIC
	Type string `json:"type"`
	// Name of the routing protocol instance.
	Name string `json:"name"`
	// Description of the routing protocol instance
	Description          *string              `json:"description,omitempty"`
	Ipv4                 *RoutingProtocolIpv4 `json:"ipv4,omitempty"`
	Ipv6                 *RoutingProtocolIpv6 `json:"ipv6,omitempty"`
	ChangeLog            ChangeLog            `json:"changeLog"`
	AdditionalProperties map[string]interface{}
}

type _RoutingProtocolReadModelStatic RoutingProtocolReadModelStatic

// NewRoutingProtocolReadModelStatic instantiates a new RoutingProtocolReadModelStatic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingProtocolReadModelStatic(type_ string, name string, changeLog ChangeLog) *RoutingProtocolReadModelStatic {
	this := RoutingProtocolReadModelStatic{}
	this.Type = type_
	this.Name = name
	this.ChangeLog = changeLog
	return &this
}

// NewRoutingProtocolReadModelStaticWithDefaults instantiates a new RoutingProtocolReadModelStatic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingProtocolReadModelStaticWithDefaults() *RoutingProtocolReadModelStatic {
	this := RoutingProtocolReadModelStatic{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *RoutingProtocolReadModelStatic) SetTags(v []string) {
	o.Tags = v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *RoutingProtocolReadModelStatic) SetHref(v string) {
	o.Href = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *RoutingProtocolReadModelStatic) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value
func (o *RoutingProtocolReadModelStatic) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RoutingProtocolReadModelStatic) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *RoutingProtocolReadModelStatic) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoutingProtocolReadModelStatic) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutingProtocolReadModelStatic) SetDescription(v string) {
	o.Description = &v
}

// GetIpv4 returns the Ipv4 field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetIpv4() RoutingProtocolIpv4 {
	if o == nil || IsNil(o.Ipv4) {
		var ret RoutingProtocolIpv4
		return ret
	}
	return *o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetIpv4Ok() (*RoutingProtocolIpv4, bool) {
	if o == nil || IsNil(o.Ipv4) {
		return nil, false
	}
	return o.Ipv4, true
}

// HasIpv4 returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasIpv4() bool {
	if o != nil && !IsNil(o.Ipv4) {
		return true
	}

	return false
}

// SetIpv4 gets a reference to the given RoutingProtocolIpv4 and assigns it to the Ipv4 field.
func (o *RoutingProtocolReadModelStatic) SetIpv4(v RoutingProtocolIpv4) {
	o.Ipv4 = &v
}

// GetIpv6 returns the Ipv6 field value if set, zero value otherwise.
func (o *RoutingProtocolReadModelStatic) GetIpv6() RoutingProtocolIpv6 {
	if o == nil || IsNil(o.Ipv6) {
		var ret RoutingProtocolIpv6
		return ret
	}
	return *o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetIpv6Ok() (*RoutingProtocolIpv6, bool) {
	if o == nil || IsNil(o.Ipv6) {
		return nil, false
	}
	return o.Ipv6, true
}

// HasIpv6 returns a boolean if a field has been set.
func (o *RoutingProtocolReadModelStatic) HasIpv6() bool {
	if o != nil && !IsNil(o.Ipv6) {
		return true
	}

	return false
}

// SetIpv6 gets a reference to the given RoutingProtocolIpv6 and assigns it to the Ipv6 field.
func (o *RoutingProtocolReadModelStatic) SetIpv6(v RoutingProtocolIpv6) {
	o.Ipv6 = &v
}

// GetChangeLog returns the ChangeLog field value
func (o *RoutingProtocolReadModelStatic) GetChangeLog() ChangeLog {
	if o == nil {
		var ret ChangeLog
		return ret
	}

	return o.ChangeLog
}

// GetChangeLogOk returns a tuple with the ChangeLog field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolReadModelStatic) GetChangeLogOk() (*ChangeLog, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeLog, true
}

// SetChangeLog sets field value
func (o *RoutingProtocolReadModelStatic) SetChangeLog(v ChangeLog) {
	o.ChangeLog = v
}

func (o RoutingProtocolReadModelStatic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingProtocolReadModelStatic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Ipv4) {
		toSerialize["ipv4"] = o.Ipv4
	}
	if !IsNil(o.Ipv6) {
		toSerialize["ipv6"] = o.Ipv6
	}
	toSerialize["changeLog"] = o.ChangeLog

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoutingProtocolReadModelStatic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"changeLog",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingProtocolReadModelStatic := _RoutingProtocolReadModelStatic{}

	err = json.Unmarshal(data, &varRoutingProtocolReadModelStatic)

	if err != nil {
		return err
	}

	*o = RoutingProtocolReadModelStatic(varRoutingProtocolReadModelStatic)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "href")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "ipv4")
		delete(additionalProperties, "ipv6")
		delete(additionalProperties, "changeLog")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoutingProtocolReadModelStatic struct {
	value *RoutingProtocolReadModelStatic
	isSet bool
}

func (v NullableRoutingProtocolReadModelStatic) Get() *RoutingProtocolReadModelStatic {
	return v.value
}

func (v *NullableRoutingProtocolReadModelStatic) Set(val *RoutingProtocolReadModelStatic) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingProtocolReadModelStatic) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingProtocolReadModelStatic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingProtocolReadModelStatic(val *RoutingProtocolReadModelStatic) *NullableRoutingProtocolReadModelStatic {
	return &NullableRoutingProtocolReadModelStatic{value: val, isSet: true}
}

func (v NullableRoutingProtocolReadModelStatic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingProtocolReadModelStatic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
