/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the ASide type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ASide{}

// ASide struct for ASide
type ASide struct {
	Type                 string       `json:"type"`
	Service              ASideService `json:"service"`
	AdditionalProperties map[string]interface{}
}

type _ASide ASide

// NewASide instantiates a new ASide object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewASide(type_ string, service ASideService) *ASide {
	this := ASide{}
	this.Type = type_
	this.Service = service
	return &this
}

// NewASideWithDefaults instantiates a new ASide object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewASideWithDefaults() *ASide {
	this := ASide{}
	return &this
}

// GetType returns the Type field value
func (o *ASide) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ASide) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ASide) SetType(v string) {
	o.Type = v
}

// GetService returns the Service field value
func (o *ASide) GetService() ASideService {
	if o == nil {
		var ret ASideService
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *ASide) GetServiceOk() (*ASideService, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *ASide) SetService(v ASideService) {
	o.Service = v
}

func (o ASide) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ASide) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["service"] = o.Service

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ASide) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"service",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varASide := _ASide{}

	err = json.Unmarshal(data, &varASide)

	if err != nil {
		return err
	}

	*o = ASide(varASide)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "service")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableASide struct {
	value *ASide
	isSet bool
}

func (v NullableASide) Get() *ASide {
	return v.value
}

func (v *NullableASide) Set(val *ASide) {
	v.value = val
	v.isSet = true
}

func (v NullableASide) IsSet() bool {
	return v.isSet
}

func (v *NullableASide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableASide(val *ASide) *NullableASide {
	return &NullableASide{value: val, isSet: true}
}

func (v NullableASide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableASide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
