/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the ServiceCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceCreateResponse{}

// ServiceCreateResponse struct for ServiceCreateResponse
type ServiceCreateResponse struct {
	Name        *string     `json:"name,omitempty"`
	Description *string     `json:"description,omitempty"`
	Type        ServiceType `json:"type"`
	// Collection of service connections uuids
	Connections     []Connection           `json:"connections"`
	RoutingProtocol RoutingProtocolRequest `json:"routingProtocol"`
	Order           *ServiceOrderRequest   `json:"order,omitempty"`
	// Service identifier
	Uuid                 string       `json:"uuid"`
	State                ServiceState `json:"state"`
	AdditionalProperties map[string]interface{}
}

type _ServiceCreateResponse ServiceCreateResponse

// NewServiceCreateResponse instantiates a new ServiceCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceCreateResponse(type_ ServiceType, connections []Connection, routingProtocol RoutingProtocolRequest, uuid string, state ServiceState) *ServiceCreateResponse {
	this := ServiceCreateResponse{}
	this.Type = type_
	this.Connections = connections
	this.RoutingProtocol = routingProtocol
	this.Uuid = uuid
	this.State = state
	return &this
}

// NewServiceCreateResponseWithDefaults instantiates a new ServiceCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceCreateResponseWithDefaults() *ServiceCreateResponse {
	this := ServiceCreateResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceCreateResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceCreateResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceCreateResponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceCreateResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceCreateResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceCreateResponse) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value
func (o *ServiceCreateResponse) GetType() ServiceType {
	if o == nil {
		var ret ServiceType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetTypeOk() (*ServiceType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ServiceCreateResponse) SetType(v ServiceType) {
	o.Type = v
}

// GetConnections returns the Connections field value
func (o *ServiceCreateResponse) GetConnections() []Connection {
	if o == nil {
		var ret []Connection
		return ret
	}

	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetConnectionsOk() ([]Connection, bool) {
	if o == nil {
		return nil, false
	}
	return o.Connections, true
}

// SetConnections sets field value
func (o *ServiceCreateResponse) SetConnections(v []Connection) {
	o.Connections = v
}

// GetRoutingProtocol returns the RoutingProtocol field value
func (o *ServiceCreateResponse) GetRoutingProtocol() RoutingProtocolRequest {
	if o == nil {
		var ret RoutingProtocolRequest
		return ret
	}

	return o.RoutingProtocol
}

// GetRoutingProtocolOk returns a tuple with the RoutingProtocol field value
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetRoutingProtocolOk() (*RoutingProtocolRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingProtocol, true
}

// SetRoutingProtocol sets field value
func (o *ServiceCreateResponse) SetRoutingProtocol(v RoutingProtocolRequest) {
	o.RoutingProtocol = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ServiceCreateResponse) GetOrder() ServiceOrderRequest {
	if o == nil || IsNil(o.Order) {
		var ret ServiceOrderRequest
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetOrderOk() (*ServiceOrderRequest, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ServiceCreateResponse) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given ServiceOrderRequest and assigns it to the Order field.
func (o *ServiceCreateResponse) SetOrder(v ServiceOrderRequest) {
	o.Order = &v
}

// GetUuid returns the Uuid field value
func (o *ServiceCreateResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ServiceCreateResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetState returns the State field value
func (o *ServiceCreateResponse) GetState() ServiceState {
	if o == nil {
		var ret ServiceState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ServiceCreateResponse) GetStateOk() (*ServiceState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ServiceCreateResponse) SetState(v ServiceState) {
	o.State = v
}

func (o ServiceCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["type"] = o.Type
	toSerialize["connections"] = o.Connections
	toSerialize["routingProtocol"] = o.RoutingProtocol
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	toSerialize["uuid"] = o.Uuid
	toSerialize["state"] = o.State

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"connections",
		"routingProtocol",
		"uuid",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceCreateResponse := _ServiceCreateResponse{}

	err = json.Unmarshal(data, &varServiceCreateResponse)

	if err != nil {
		return err
	}

	*o = ServiceCreateResponse(varServiceCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "type")
		delete(additionalProperties, "connections")
		delete(additionalProperties, "routingProtocol")
		delete(additionalProperties, "order")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceCreateResponse struct {
	value *ServiceCreateResponse
	isSet bool
}

func (v NullableServiceCreateResponse) Get() *ServiceCreateResponse {
	return v.value
}

func (v *NullableServiceCreateResponse) Set(val *ServiceCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCreateResponse(val *ServiceCreateResponse) *NullableServiceCreateResponse {
	return &NullableServiceCreateResponse{value: val, isSet: true}
}

func (v NullableServiceCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
