/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// RoutingProtocolRequestBgpAllOfExportPolicy Denotes which routes should be advertised to the internet
type RoutingProtocolRequestBgpAllOfExportPolicy string

// List of RoutingProtocolRequestBgp_allOf_exportPolicy
const (
	ROUTINGPROTOCOLREQUESTBGPALLOFEXPORTPOLICY_FULL         RoutingProtocolRequestBgpAllOfExportPolicy = "FULL"
	ROUTINGPROTOCOLREQUESTBGPALLOFEXPORTPOLICY_DEFAULT      RoutingProtocolRequestBgpAllOfExportPolicy = "DEFAULT"
	ROUTINGPROTOCOLREQUESTBGPALLOFEXPORTPOLICY_FULL_DEFAULT RoutingProtocolRequestBgpAllOfExportPolicy = "FULL_DEFAULT"
	ROUTINGPROTOCOLREQUESTBGPALLOFEXPORTPOLICY_PARTIAL      RoutingProtocolRequestBgpAllOfExportPolicy = "PARTIAL"
)

// All allowed values of RoutingProtocolRequestBgpAllOfExportPolicy enum
var AllowedRoutingProtocolRequestBgpAllOfExportPolicyEnumValues = []RoutingProtocolRequestBgpAllOfExportPolicy{
	"FULL",
	"DEFAULT",
	"FULL_DEFAULT",
	"PARTIAL",
}

func (v *RoutingProtocolRequestBgpAllOfExportPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RoutingProtocolRequestBgpAllOfExportPolicy(value)
	for _, existing := range AllowedRoutingProtocolRequestBgpAllOfExportPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RoutingProtocolRequestBgpAllOfExportPolicy", value)
}

// NewRoutingProtocolRequestBgpAllOfExportPolicyFromValue returns a pointer to a valid RoutingProtocolRequestBgpAllOfExportPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRoutingProtocolRequestBgpAllOfExportPolicyFromValue(v string) (*RoutingProtocolRequestBgpAllOfExportPolicy, error) {
	ev := RoutingProtocolRequestBgpAllOfExportPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RoutingProtocolRequestBgpAllOfExportPolicy: valid values are %v", v, AllowedRoutingProtocolRequestBgpAllOfExportPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RoutingProtocolRequestBgpAllOfExportPolicy) IsValid() bool {
	for _, existing := range AllowedRoutingProtocolRequestBgpAllOfExportPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RoutingProtocolRequestBgp_allOf_exportPolicy value
func (v RoutingProtocolRequestBgpAllOfExportPolicy) Ptr() *RoutingProtocolRequestBgpAllOfExportPolicy {
	return &v
}

type NullableRoutingProtocolRequestBgpAllOfExportPolicy struct {
	value *RoutingProtocolRequestBgpAllOfExportPolicy
	isSet bool
}

func (v NullableRoutingProtocolRequestBgpAllOfExportPolicy) Get() *RoutingProtocolRequestBgpAllOfExportPolicy {
	return v.value
}

func (v *NullableRoutingProtocolRequestBgpAllOfExportPolicy) Set(val *RoutingProtocolRequestBgpAllOfExportPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingProtocolRequestBgpAllOfExportPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingProtocolRequestBgpAllOfExportPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingProtocolRequestBgpAllOfExportPolicy(val *RoutingProtocolRequestBgpAllOfExportPolicy) *NullableRoutingProtocolRequestBgpAllOfExportPolicy {
	return &NullableRoutingProtocolRequestBgpAllOfExportPolicy{value: val, isSet: true}
}

func (v NullableRoutingProtocolRequestBgpAllOfExportPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingProtocolRequestBgpAllOfExportPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
